version: '3'
services:
  statusd:
    image: "statusteam/status-go"
    volumes:
      - ./data/statusd-data:/statusd-data
    command: statusd -shh -networkid=1 -discovery=true -metrics -ipc -standalone=false -topic.search=whisper=1,4

  geth_exporter:
    depends_on:
      - statusd
    build:
      context: ../
      dockerfile: _assets/Dockerfile
    volumes:
      - ./data/statusd-data:/statusd-data
    command: geth_exporter -ipc /statusd-data/geth.ipc
    ports:
     - "9200:9200"
    restart: always

  prometheus:
    depends_on:
      - geth_exporter
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus-data"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./data/prometheus:/prometheus-data
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
